# Generated by Django 5.2.17 on 2026-08-31 10:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('aggregate_type', models.CharField(db_index=True, max_length=80)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('event_version', models.IntegerField(default=1)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DISPATCHED', 'Dispatched'), ('DEAD', 'Dead')], db_index=True, default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'db_table': 'outbox_events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='outbox_even_status_b8536e_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_even_aggrega_d56a15_idx')],
            },
        ),
    ]
