# Generated by Django 5.2.17 on 2026-08-31 10:44

import apps.tables.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_code', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('qr_token', models.CharField(db_index=True, default=apps.tables.models.generate_secure_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Table',
                'verbose_name_plural': 'Restaurant Tables',
                'db_table': 'restaurant_tables',
                'ordering': ['sort_order', 'table_code'],
            },
        ),
        migrations.CreateModel(
            name='TableSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.CharField(db_index=True, default=apps.tables.models.generate_secure_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('BILL_REQUESTED', 'Bill Requested'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30)),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('bill_requested_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_sessions', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Table Session',
                'verbose_name_plural': 'Table Sessions',
                'db_table': 'table_sessions',
            },
        ),
        migrations.AddConstraint(
            model_name='restauranttable',
            constraint=models.UniqueConstraint(fields=('restaurant', 'table_code'), name='unique_restaurant_table_code'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['table', 'status'], name='table_sessi_table_i_b8fe13_idx'),
        ),
        migrations.AddIndex(
            model_name='tablesession',
            index=models.Index(fields=['opened_at'], name='table_sessi_opened__142ef6_idx'),
        ),
    ]
