# Generated by Django 5.2.17 on 2026-10-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='authorized_device_tokens',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='primary_device_token',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
