# Generated by Django 5.2.17 on 2026-10-04 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('tables', '0002_tablesession_authorized_device_tokens_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableActivationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('guest_count', models.PositiveIntegerField(default=2)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_activations', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_requests', to='tables.restauranttable')),
            ],
            options={
                'verbose_name': 'Table Activation Request',
                'verbose_name_plural': 'Table Activation Requests',
                'db_table': 'table_activation_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['table', 'status'], name='table_activ_table_i_adfa07_idx'), models.Index(fields=['status', 'requested_at'], name='table_activ_status_c0d3a5_idx')],
            },
        ),
    ]
