# Generated by Django 5.2.17 on 2026-08-31 10:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=100)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('response_status', models.IntegerField(default=200)),
                ('response_body', models.JSONField(default=dict)),
                ('resource_type', models.CharField(blank=True, max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_records',
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='unique_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('source', models.CharField(choices=[('CUSTOMER', 'Customer Dine-In PWA'), ('CASHIER', 'Cashier POS')], default='CUSTOMER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_CASHIER_CONFIRMATION', 'Waiting Cashier Confirmation'), ('CONFIRMED', 'Confirmed (Sent to Kitchen)'), ('PREPARING', 'Preparing in Kitchen'), ('READY', 'Ready to Serve'), ('SERVED', 'Served to Table'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected by Cashier'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING_CASHIER_CONFIRMATION', max_length=40)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.tablesession')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_name_snapshot', models.CharField(max_length=150)),
                ('sku_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=40, null=True)),
                ('to_status', models.CharField(max_length=40)),
                ('actor_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('STAFF', 'Staff'), ('SYSTEM', 'System')], default='CUSTOMER', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ordering.order')),
            ],
            options={
                'verbose_name': 'Order Status History',
                'verbose_name_plural': 'Order Status Histories',
                'db_table': 'order_status_history',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table_session', 'created_at'], name='orders_table_s_516dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['confirmed_at'], name='orders_confirm_0043cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('table_session', 'idempotency_key'), name='unique_session_idempotency_order'),
        ),
    ]
